name: Update README Last Modified Date

on:
  push:
    branches:
      - '**'   # Matches all branches

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get last commit date
        run: |
          LAST_DATE=$(git log -1 --format=%cd --date=short)
          echo "LAST_DATE=$LAST_DATE" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s|Last updated: .*|Last updated: $LAST_DATE|" README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README last modified date"
          git push
